export const defaultData = {
  hero: {
    name: "Alex Chen",
    role: "Full Stack Developer",
    tagline: "Building the future, one commit at a time.",
    subtitle: "Crafting digital experiences that push the boundaries of what's possible.",
    ctaPrimary: "View Projects",
    ctaSecondary: "Open Terminal",
    avatar: "/avatar.png",
  },
  about: {
    bio: "I'm a passionate full-stack developer with 5+ years of experience building scalable web applications. I specialize in React, Node.js, and cloud infrastructure, with a deep love for performance optimization and clean architecture.",
    location: "San Francisco, CA",
    email: "alex@devportfolio.io",
    availability: "Open to opportunities",
    experience: [
      {
        year: "2023 — Now",
        role: "Senior Full Stack Engineer",
        company: "TechCorp Inc.",
        description: "Leading development of next-gen SaaS platform serving 100K+ users.",
      },
      {
        year: "2021 — 2023",
        role: "Frontend Engineer",
        company: "StartupXYZ",
        description: "Built and scaled React applications from 0 to 50K users.",
      },
      {
        year: "2019 — 2021",
        role: "Junior Developer",
        company: "Agency Digital",
        description: "Developed client websites and e-commerce solutions.",
      },
    ],
    stats: [
      { label: "Years Experience", value: "5+" },
      { label: "Projects Shipped", value: "80+" },
      { label: "Happy Clients", value: "30+" },
      { label: "Coffee Cups", value: "∞" },
    ],
  },
  skills: [
    { name: "React / Next.js", category: "Frontend", icon: "⚛️" },
    { name: "TypeScript", category: "Language", icon: "📘" },
    { name: "Node.js", category: "Backend", icon: "🟢" },
    { name: "Python", category: "Language", icon: "🐍" },
    { name: "PostgreSQL", category: "Database", icon: "🗄️" },
    { name: "Redis", category: "Database", icon: "🔴" },
    { name: "Docker", category: "DevOps", icon: "🐳" },
    { name: "AWS", category: "Cloud", icon: "☁️" },
    { name: "GraphQL", category: "API", icon: "◈" },
    { name: "Three.js", category: "3D/WebGL", icon: "🎮" },
    { name: "Framer Motion", category: "Animation", icon: "✨" },
    { name: "Tailwind CSS", category: "Frontend", icon: "💨" },
  ],
  projects: [
    {
      id: 1,
      title: "NeuralDash",
      description: "An AI-powered analytics dashboard with real-time data visualization and predictive insights for enterprise teams.",
      tags: ["React", "Python", "TensorFlow", "PostgreSQL"],
      image: "/projects/neuraldash.jpg",
      github: "https://github.com",
      live: "https://example.com",
      category: "AI",
      featured: true,
    },
    {
      id: 2,
      title: "CipherChat",
      description: "End-to-end encrypted messaging platform with zero-knowledge architecture and self-destructing messages.",
      tags: ["Next.js", "WebRTC", "Node.js", "Redis"],
      image: "/projects/cipherchat.jpg",
      github: "https://github.com",
      live: "https://example.com",
      category: "Security",
      featured: true,
    },
    {
      id: 3,
      title: "VoxForge",
      description: "A 3D audio visualization tool that converts music into interactive geometric art using WebAudio API.",
      tags: ["Three.js", "WebAudio", "GSAP", "React"],
      image: "/projects/voxforge.jpg",
      github: "https://github.com",
      live: "https://example.com",
      category: "Creative",
      featured: false,
    },
    {
      id: 4,
      title: "OrbitalDB",
      description: "Distributed database management system with visual schema design and real-time collaboration features.",
      tags: ["Rust", "PostgreSQL", "WebSocket", "React"],
      image: "/projects/orbitaldb.jpg",
      github: "https://github.com",
      live: "https://example.com",
      category: "Backend",
      featured: false,
    },
  ],
  social: {
    github: "https://github.com",
    twitter: "https://twitter.com",
    linkedin: "https://linkedin.com",
    email: "alex@devportfolio.io",
  },
};

export type PortfolioData = typeof defaultData;
